version: 2

before:
  hooks:
  - go mod tidy
  - go mod download

builds:
- env:
  - CGO_ENABLED=1
  goos:
  - linux
  goarch:
  - amd64
  binary: mouseless
  ldflags:
  - -s -w
  - -X main.version={{.Version}}
  main: .

archives:
- formats: [ tar.gz ]
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  files:
  - mouseless*
  wrap_in_directory: false

checksum:
  name_template: "checksums.txt"

release:
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"